modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="epicfight_improve"
version="1.0.0"
displayName="史诗战斗：改进"
authors="XcS"
credits="_P1nero（倒地免疫、完美闪避残影）GuHao（格挡修复）"
logoFile="LOGO.png"
description = '''
对原本史诗战斗的机制进行优化，使得玩家有更好的战斗体验。
'''
[[dependencies.epicfight_improve]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.epicfight_improve]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.epicfight_improve]]
modId="epicfight"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"